### PR TITLE
It is not enough tesed, but also have some bugs...

### PR DESCRIPTION
**Pull request by tomofu74**
For humhub ver.1.5.1. tested in a few days.

### CODE REVIEW

**Comment by luke-** [comment]
Great!

is there something against merging the PR?
The current version is not finished yet.

**Comment by Carl2213** [comment]
@tomofu74 can you explain what you've done here? Because the main privacy issue still exists. You can share private posts from private space and make them appear on a public wall.

And there's now an additional issue that I don't understand: The share button doesn't appear on all posts. It seems to appear at random, regardless of whether the content is public or not (which would be ideal) or whether I'm the author of the content.

**Comment by Carl2213** [comment]
There's another version [here](https://github.com/ArchBlood/humhub-sharebetween) that's supposed to be more advanced but from what I can tell it has all the same issues.

Maybe @ArchBlood knows the difference since he forked it.

**Comment by tomofu74** [comment]
Hi, @Carl2213 . Thank you for your interesting.
I made it work with Ver.1.5 as it has had been, and fork it without creating some tests code.
The module I wanted was created by myself referring to this. And it's not open to the public, because it was costumed to my client's.

**Comment by ArchBlood** [comment]
Hello, thanks for the ping @Carl2213 all I can say is the person that pushed the repo has already given his explanation, although looking through the module it also doesn't support Pjax or the methods were broken for model actions, looking over the AjaxButton widget I see it is very old, going back to `0.20.beta-1`, I've also looked through some of Yii2 posts and see that `data-method` has better use within `Html::a()`, although I myself wouldn't know how to implement such a thing into this module. :thinking:

> **The reason why I created a new repository with this build and didn't do a collaboration, is that the Share action here acts differently from the script provided by humhub-contrib/sharebetween**

**Comment by Carl2213** [comment]
Yes @ArchBlood I did see the Readme, but I can't figure out how his script "acts differently". I see a lot of extra code relating to groups and followers, but from my brief testing it seems to work the same way. Except for the reported bug that the original post can no longer be reported.

I was just sharing bugs/missing functionality here for reference. For myself or anyone else that wants to work on the module.

**Pull request closed without merging**
